apisix:
  node_listen:
    - 9080
  enable_admin: false
  enable_control: false
  enable_ipv6: false
  dns_resolver:
    - 127.0.0.11

nginx_config:
  worker_processes: 1
  error_log_level: warn
  http:
    client_max_body_size: 16m

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
